version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: assetku_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sistemasetku
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assetku_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=db_sistemasetku
      - SERVER_PORT=8080
      - JWT_SECRET=sistemasetku_secret_production_key_2026
    depends_on:
      - db

volumes:
  mysql_data:
